# Generated by Django 5.1 on 2024-09-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('VPAA', 'Vice President of Academic Affairs'), ('IDEALS', 'Ideals'), ('HR', 'HR'), ('DEANS', 'Deans')], default='DEANS', max_length=10),
        ),
    ]
