# Generated by Django 5.1.1 on 2024-09-18 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_datentry_question_1_alter_datentry_question_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datentry',
            name='question_1',
            field=models.IntegerField(default=0, help_text='The instructor has set clear standards regarding their timeliness in responding to messages.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_10',
            field=models.IntegerField(default=0, help_text='The instructor interactively engages learners in a variety of instructional delivery methods.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_12',
            field=models.IntegerField(default=0, help_text='The instructor provides students access to resources that enrich the course content.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_13',
            field=models.IntegerField(default=0, help_text='The instructor demonstrates a thorough knowledge of the subject matter.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_14',
            field=models.IntegerField(default=0, help_text='The instructor provides examples  case studies  or problem sets that required higher-order thinking skills.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_15',
            field=models.IntegerField(default=0, help_text='The instructor explains the significance of the lessons.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_16',
            field=models.IntegerField(default=0, help_text='Tasks and assessments increase their level of challenge.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_17',
            field=models.IntegerField(default=0, help_text='The instructor provides examples or models of what is expected.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_18',
            field=models.IntegerField(default=0, help_text='Course outcomes are clearly presented.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_19',
            field=models.IntegerField(default=0, help_text='Course deadlines are clearly set.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_2',
            field=models.IntegerField(default=0, help_text='The instructor has provided the appropriate information and contact details for technical concerns.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_20',
            field=models.IntegerField(default=0, help_text='Provides reminders regarding upcoming deadlines.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_21',
            field=models.IntegerField(default=0, help_text='The instructor provides clear guidelines and/or rubrics of the learning activities.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_22',
            field=models.IntegerField(default=0, help_text='The instructor provides Information Feedback (Evaluation of Work  Answers to Questions  Comments on Submissions).', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_23',
            field=models.IntegerField(default=0, help_text='The instructor provides Acknowledgment Feedback (acknowledges communication sent by student).', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_24',
            field=models.IntegerField(default=0, help_text='The instructor returns assessments in a timely fashion.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_25',
            field=models.IntegerField(default=0, help_text='The instructor engages students in learning activities that address a variety of learning styles and preferences.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_26',
            field=models.IntegerField(default=0, help_text='The instructor adapts learning activities to accommodate student&#39s needs.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_27',
            field=models.IntegerField(default=0, help_text='Quality of work is praised.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_28',
            field=models.IntegerField(default=0, help_text='The instructor is effective in helping students develop their knowledge  skills  and personalities enabling them to achieve the intended learning outcomes.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_29',
            field=models.IntegerField(default=0, help_text='Course assessments are authentic and measure Higher-Order Thinking Skills.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_3',
            field=models.IntegerField(default=0, help_text='The instructor showed interest in student progress.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_30',
            field=models.IntegerField(default=0, help_text='The instructor provides sufficient attempts in the attainment of learning outcomes.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_31',
            field=models.IntegerField(default=0, help_text='Comments on the Instructor.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_32',
            field=models.IntegerField(default=0, help_text='Comments on the Course.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_4',
            field=models.IntegerField(default=0, help_text='The instructor encourages learners to participate.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_5',
            field=models.IntegerField(default=0, help_text='The instructor implements Small Group Discussions (Breakout Rooms).', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_6',
            field=models.IntegerField(default=0, help_text='The instructor provides equal opportunities for students to share ideas and viewpoints.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_7',
            field=models.IntegerField(default=0, help_text='The instructor requires learners to participate.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_8',
            field=models.IntegerField(default=0, help_text='The instructor provides platforms for Small Group Discussions.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='datentry',
            name='question_9',
            field=models.IntegerField(default=0, help_text='Tasks deployed require collaboration among students.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
