# Generated by Django 5.1.1 on 2024-09-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_datentry_question_1_alter_datentry_question_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datentry',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Not specified', max_length=1),
        ),
    ]
