# Generated by Django 5.1.1 on 2024-09-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_datentry_uploadcsv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcsv',
            name='date_start',
            field=models.CharField(max_length=255),
        ),
    ]
