# Generated by Django 5.1.1 on 2024-09-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_uploadcsv_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcsv',
            name='date_close',
            field=models.CharField(max_length=255),
        ),
    ]
