# Generated by Django 5.1.1 on 2024-09-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_uploadcsv_date_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadcsv',
            name='crs_num',
            field=models.CharField(default='', max_length=255),
        ),
    ]
