# Generated by Django 5.1.1 on 2024-09-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_uploadcsv_crs_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcsv',
            name='t_submit',
            field=models.CharField(max_length=255),
        ),
    ]
