# Generated by Django 5.1.1 on 2024-09-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_uploadcsv_t_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcsv',
            name='mobile',
            field=models.CharField(max_length=255),
        ),
    ]
