# Generated by Django 5.1.1 on 2024-09-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_uploadcsv_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcsv',
            name='crs_num',
            field=models.CharField(max_length=255),
        ),
    ]
