# Generated by Django 5.1.1 on 2024-09-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_uploadcsv_crs_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcsv',
            name='grad_year',
            field=models.CharField(max_length=255),
        ),
    ]
