# Generated by Django 5.1.1 on 2024-09-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_uploadcsv_grad_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_31',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_32',
            field=models.CharField(max_length=255),
        ),
    ]
