# Generated by Django 5.1.2 on 2024-10-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_customuser_user_type_alter_uploadcsv_eval_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadcsv',
            name='term',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
