# Generated by Django 5.1.2 on 2024-10-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_uploadcsv_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('ATYCB', 'ATYCB'), ('CAS', 'CAS'), ('CEA', 'CEA'), ('CCIS', 'CCIS')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('VPAA', 'Vice President of Academic Affairs'), ('IDEALS', 'Ideals'), ('QAEO', 'QAEO'), ('DEANS', 'Deans')], max_length=20),
        ),
    ]
