# Generated by Django 5.1.2 on 2024-10-31 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_customuser_department_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('VPAA', 'Vice President of Academic Affairs'), ('IDEALS', 'Ideals'), ('QAEO', 'QAEO'), ('DEANS', 'Deans'), ('ATYCB', 'ATYCB Dean'), ('CAS', 'CAS Dean'), ('CEA', 'CEA Dean'), ('CCIS', 'CCIS Dean')], max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_11',
            field=models.IntegerField(default=0, help_text='The instructor deploys various active learning techniques (role-playing , case studies, etc.)', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_22',
            field=models.IntegerField(default=0, help_text='The instructor provides Information Feedback (Evaluation of Work, Answers to Questions, etc.).', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_26',
            field=models.IntegerField(default=0, help_text='The instructor adapts learning activities to accommodate students needs.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_28',
            field=models.IntegerField(default=0, help_text='Instructor is effective in helping students develop their knowledge, skills, & personalities.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_31',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_32',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
