# Generated by Django 5.1.2 on 2024-10-31 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_customuser_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_1',
            field=models.IntegerField(blank=True, default=0, help_text='The instructor has set clear standards regarding their timeliness in responding to messages.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_10',
            field=models.IntegerField(blank=True, default=0, help_text='The instructor interactively engages learners in a variety of instructional delivery methods.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_11',
            field=models.IntegerField(blank=True, default=0, help_text='The instructor deploys various active learning techniques (role-playing , case studies, etc.)', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_12',
            field=models.IntegerField(blank=True, default=0, help_text='The instructor provides students access to resources that enrich the course content.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_13',
            field=models.IntegerField(blank=True, default=0, help_text='The instructor demonstrates a thorough knowledge of the subject matter.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_14',
            field=models.IntegerField(blank=True, default=0, help_text='The instructor provides examples  case studies  or problem sets that required higher-order thinking skills.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_15',
            field=models.IntegerField(blank=True, default=0, help_text='The instructor explains the significance of the lessons.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_16',
            field=models.IntegerField(blank=True, default=0, help_text='Tasks and assessments increase their level of challenge.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_17',
            field=models.IntegerField(blank=True, default=0, help_text='The instructor provides examples or models of what is expected.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_18',
            field=models.IntegerField(blank=True, default=0, help_text='Course outcomes are clearly presented.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_19',
            field=models.IntegerField(blank=True, default=0, help_text='Course deadlines are clearly set.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_2',
            field=models.IntegerField(blank=True, default=0, help_text='The instructor has provided the appropriate information and contact details for technical concerns.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_20',
            field=models.IntegerField(blank=True, default=0, help_text='Provides reminders regarding upcoming deadlines.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_21',
            field=models.IntegerField(blank=True, default=0, help_text='The instructor provides clear guidelines and/or rubrics of the learning activities.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_22',
            field=models.IntegerField(blank=True, default=0, help_text='The instructor provides Information Feedback (Evaluation of Work, Answers to Questions, etc.).', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_23',
            field=models.IntegerField(blank=True, default=0, help_text='The instructor provides Acknowledgment Feedback (acknowledges communication sent by student).', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_24',
            field=models.IntegerField(blank=True, default=0, help_text='The instructor returns assessments in a timely fashion.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_25',
            field=models.IntegerField(blank=True, default=0, help_text='The instructor engages students in learning activities that address a variety of learning styles and preferences.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_26',
            field=models.IntegerField(blank=True, default=0, help_text='The instructor adapts learning activities to accommodate students needs.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_27',
            field=models.IntegerField(blank=True, default=0, help_text='Quality of work is praised.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_28',
            field=models.IntegerField(blank=True, default=0, help_text='Instructor is effective in helping students develop their knowledge, skills, & personalities.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_29',
            field=models.IntegerField(blank=True, default=0, help_text='Course assessments are authentic and measure Higher-Order Thinking Skills.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_3',
            field=models.IntegerField(blank=True, default=0, help_text='The instructor showed interest in student progress.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_30',
            field=models.IntegerField(blank=True, default=0, help_text='The instructor provides sufficient attempts in the attainment of learning outcomes.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_4',
            field=models.IntegerField(blank=True, default=0, help_text='The instructor encourages learners to participate.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_5',
            field=models.IntegerField(blank=True, default=0, help_text='The instructor implements Small Group Discussions (Breakout Rooms).', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_6',
            field=models.IntegerField(blank=True, default=0, help_text='The instructor provides equal opportunities for students to share ideas and viewpoints.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_7',
            field=models.IntegerField(blank=True, default=0, help_text='The instructor requires learners to participate.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_8',
            field=models.IntegerField(blank=True, default=0, help_text='The instructor provides platforms for Small Group Discussions.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='question_9',
            field=models.IntegerField(blank=True, default=0, help_text='Tasks deployed require collaboration among students.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
