# Generated by Django 5.1.2 on 2024-11-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('VPAA', 'Vice President of Academic Affairs'), ('IDEALS', 'Ideals'), ('QAEO', 'QAEO'), ('HR', 'HR'), ('DEANS', 'Deans'), ('ATYCB', 'ATYCB Dean'), ('CHS', 'CHS Dean'), ('CAS', 'CAS Dean'), ('CEA', 'CEA Dean'), ('CCIS', 'CCIS Dean')], max_length=20),
        ),
    ]
